### ISSUE TITLE
Review UsergridAuth.expiresIn

### ISSUE THREAD

**Issue by r3mus** [RobertWalsh/UsergridSDK#1]
For review:

`UsergridAuth.expiresIn` may need to be `UsergridAuth.expiresAt` or `UsergridAuth.expiry` by taking the `expires_in` property from the token request and calculating an expiration timestamp. Otherwise we'll end up having to use a timer probably?

**Comment by RobertWalsh** [comment]
I changed to it UsergridAuth.expiresAt.
