### ISSUE TITLE
When making a payload-based request (POST, PUT), when the body is invalid, no error is thrown

### ISSUE THREAD

**Issue by r3mus** [RobertWalsh/UsergridSDK#3]
Line 69 of UsergridRequest.swift:

    if let body = jsonBody where (body is NSData || NSJSONSerialization.isValidJSONObject(body)) {
        self.jsonBody = body
    } else {
        self.jsonBody = nil
    }

There is no error thrown if the self.jsonBody is nil; we should check that if body is defined and fails the isValidJSONObject check, that something is written to the console at least, or an error returned on the callback. Instead, the request goes through and a response comes back 200 OK, but the entity is never created/updated.

**Comment by RobertWalsh** [comment]
Done.  See https://github.com/RobertWalsh/UsergridSDK/commit/6749aee71847c0955d6fbb4a3ede58d394e4f1e1
