### ISSUE TITLE
Convenience methods like .save() and .remove() should fail if .uuidOrName, .uuid, or .name are nil

### ISSUE THREAD

**Issue by r3mus** [RobertWalsh/UsergridSDK#4]
If you create a new entity and try to save it without a uuid or name, the convenience method is performed, but the entity is not updated. `response.ok` also returns true, and therefore is a false positive.

**Comment by RobertWalsh** [comment]
So all the convenience methods actually call the corresponding methods within UsergridClient.  Within those methods you will see checks for uuidOrName.  

The one method that is different is save().  That method will POST if no UUID is found and PUT if there is one there.

**Comment by RobertWalsh** [comment]
Updated the save() function in commit : https://github.com/RobertWalsh/UsergridSDK/commit/953ed316cca7fdcc490c0a46d9b5a2713d7074cc
