### ISSUE TITLE
Debug inspector should have a more readily accessible property for inspecting objects

### ISSUE THREAD

**Issue by r3mus** [RobertWalsh/UsergridSDK#7]
Take for example UsergridEntity:

<img width="334" alt="screenshot_855" src="https://cloud.githubusercontent.com/assets/1480253/12636615/15505b86-c543-11e5-87dc-6f63862b5c0f.png">

There is no easily accessible property view for accessing the contents of the entity in the debug inspector. Unsure how we could improve this, but it would be great to have at the very least an easily accessible raw JSON component for UsergridEntity, UsergridUser, UsergridResponseError, and probably UsergridResponse too (although I think that one might have something available?)

UsergridResponse should also support something like:

    response.responseJSON.rawValue // outputs stringified JSON

**Comment by RobertWalsh** [comment]
So we cant really do anything with the debugging variables and how they are shown within the variable inspector in XCode.  That will probably improve along with xcode hopefully.  

I did however add some methods to make debugging a little easier with this commit: https://github.com/RobertWalsh/UsergridSDK/commit/75b049d7e3a3ab55a0306b4001e61784b85abf92.

Now if you right click on the things like the UsergridEntity object and tell it to print the description you will see a much nicer version of things.
