### ISSUE TITLE
When logoutCurrentUser fails, currentUser and currentUser.auth are still set to nil

### ISSUE THREAD

**Issue by r3mus** [RobertWalsh/UsergridSDK#8]
UsergridClient line 315

    public func logoutCurrentUser(completion:UsergridResponseCompletion? = nil) {
        if let user = self.currentUser, uuidOrUsername = user.uuidOrUsername, token = user.auth?.accessToken {
            self.logoutUser(uuidOrUsername, token: token) { (response) -> Void in
                self.currentUser?.auth = nil
                self.currentUser = nil
                completion?(response: response)
            }
        } else {
            completion?(response:UsergridResponse(client: self, errorName: "Logout Failed.", errorDescription: "UsergridClient's currentUser is not valid."))
        }
    }

Should look more like:

    public func logoutCurrentUser(completion:UsergridResponseCompletion? = nil) {
        if let user = self.currentUser, uuidOrUsername = user.uuidOrUsername, token = user.auth?.accessToken {
            self.logoutUser(uuidOrUsername, token: token) { (response) -> Void in
                if response.ok {
                    self.currentUser?.auth = nil
                    self.currentUser = nil
                }
                completion?(response: response)
            }
        } else {
            completion?(response:UsergridResponse(client: self, errorName: "Logout Failed.", errorDescription: "UsergridClient's currentUser is not valid."))
        }
    }

Otherwise, when the logout request fails, the current user will still be set to nil and that will cause crashes!

**Comment by RobertWalsh** [comment]
Fixed with your changes in https://github.com/RobertWalsh/UsergridSDK/commit/ab672407efb97198e5823cc4608826813e04bb9a
