### ISSUE TITLE
logoutUser and other "appendPath" related functions that append a query param are url-encoding the GET query operators

### ISSUE THREAD

**Issue by r3mus** [RobertWalsh/UsergridSDK#9]
When debugging a logoutUser call:

    <NSMutableURLRequest: 0x7f8ba266c7e0> { URL: [baseUrl]/[org]/[app]/users/[uuid]/revoketoken%3Ftoken=[token] }

As you can see, the ? in the appended path is being url-encoded.

Suggest that rather than using `paths.append()` as done on line 345 of UsergridClient.swift, there should be a query string argument the same as `jsonBody` is used when building PUT and POST requests.

Something like:

    let queryParams: [String: AnyObject] = ["token": userToken]
    let request = UsergridRequest(method: .Put,
                                    baseUrl: self.clientAppURL,
                                    paths: paths,
                                    auth: self.authForRequests(),
                                    queryParams: queryParams)

**Comment by RobertWalsh** [comment]
Fixed with your changes in https://github.com/RobertWalsh/UsergridSDK/commit/ab672407efb97198e5823cc4608826813e04bb9a
